export const NOTIFICATION_TYPES = {
  PROPOSAL_ACCEPTED: 'PROPOSAL_ACCEPTED',
  PROPOSAL_REJECTED: 'PROPOSAL_REJECTED',
  PROPOSAL_COUNTERED: 'PROPOSAL_COUNTERED',
  NEW_INVESTMENT_PROPOSAL: 'NEW_INVESTMENT_PROPOSAL',
  PROPOSAL_WITHDRAWN: 'PROPOSAL_WITHDRAWN',
  CAMPAIGN_MILESTONE_UPDATE: 'CAMPAIGN_MILESTONE_UPDATE',
  STARTUP_BOOKMARKED: 'STARTUP_BOOKMARKED',
  DIRECT_MESSAGE: 'DIRECT_MESSAGE',
  VERIFICATION_APPROVED: 'VERIFICATION_APPROVED',
  VERIFICATION_REJECTED: 'VERIFICATION_REJECTED',
  VERIFICATION_PENDING: 'VERIFICATION_PENDING'
};

export function isInternalNotificationLink(link) {
  const value = String(link || '');
  return value.startsWith('tab:') || value.startsWith('/');
}
