export const NOTIFICATION_TYPES = Object.freeze({
  PROPOSAL_ACCEPTED: 'PROPOSAL_ACCEPTED',
  PROPOSAL_REJECTED: 'PROPOSAL_REJECTED',
  PROPOSAL_COUNTERED: 'PROPOSAL_COUNTERED',
  NEW_INVESTMENT_PROPOSAL: 'NEW_INVESTMENT_PROPOSAL',
  PROPOSAL_WITHDRAWN: 'PROPOSAL_WITHDRAWN',
  CAMPAIGN_MILESTONE_UPDATE: 'CAMPAIGN_MILESTONE_UPDATE',
  STARTUP_BOOKMARKED: 'STARTUP_BOOKMARKED',
  DIRECT_MESSAGE: 'DIRECT_MESSAGE',
  VERIFICATION_APPROVED: 'VERIFICATION_APPROVED',
  VERIFICATION_REJECTED: 'VERIFICATION_REJECTED',
  VERIFICATION_PENDING: 'VERIFICATION_PENDING',
  MILESTONE_FUNDING_REQUESTED: 'MILESTONE_FUNDING_REQUESTED',
  FUNDS_RELEASED: 'FUNDS_RELEASED',
  DISPUTE_OPENED: 'DISPUTE_OPENED',
  INFO: 'info',
  SUCCESS: 'success',
  WARNING: 'warning'
});

const ALLOWED = new Set(Object.values(NOTIFICATION_TYPES));

export function isNotificationType(value) {
  return ALLOWED.has(String(value || ''));
}

export function normalizeNotificationType(value) {
  const raw = String(value || 'info');
  if (ALLOWED.has(raw)) return raw;
  const upper = raw.toUpperCase();
  if (ALLOWED.has(upper)) return upper;
  return NOTIFICATION_TYPES.INFO;
}
